### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:information_source: Shift detected you do not have a CI workflow using GitHub Actions. If you would like, Shift can help you get started with the [CI Generator](https://laravelshift.com/ci-generator). Although the Shift is paid, GitHub Actions is free and having a CI workflow will improve the stability and review process for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-dump-server.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "beyondcode/laravel-dump-server": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by reppair** [comment]
We could make use of L11 support ❤️

**Comment by nik-418** [comment]
t'would be great 👍

**Comment by Redtama** [comment]
Yes please L11 support would be wonderful! ❤️

**Comment by jleonardolemos** [comment]
To merge this PR will be necessary to fix the phpunit.xml attibutes due to the phpunit update.

Screenshot from 2024-04-01 11-33-51

After upgrading my own packages i will do a PR here.

**Comment by tanerkay** [comment]
> To merge this PR will be necessary to fix the phpunit.xml attibutes due to the phpunit update.

it's not so much an upgrade, but rather added support for a newer phpunit version, in addition to the current ones

note that this package currently supports packages down to laravel 5.? and phpunit 7

**Comment by devnicolas1** [comment]
Also expecting this PR to merged. Would be great to have an update about it! :)

**Comment by renky** [comment]
> > To merge this PR will be necessary to fix the phpunit.xml attibutes due to the phpunit update.
> 
> it's not so much an upgrade, but rather added support for a newer phpunit version, in addition to the current ones
> 
> note that this package currently supports packages down to laravel 5.? and phpunit 7

Since this package doesn't really have big changes over time, I think it sould be fine for all the people out there using Laravel5 and phpunit 7 to stick with an old version. Finally it could get a new major number and drop support for older versions, but anyway, it should go forward

**Comment by flexchar** [comment]
Maybe someone could shot a kind email to them regarding this at `support@beyondco.de` ✌️

**Comment by renky** [comment]
I already contacted them right before the weekend. So let's wait...

**Pull request merged**
